import React from 'react';
import {
  X,
  ShieldCheck,
  QrCode,
  Download,
  ExternalLink,
  CheckCircle2,
  AlertTriangle,
  Building,
  Calendar,
  Layers,
  Box
} from 'lucide-react';
import { PropertyPassportData } from '../../types/intelligence';
import { DataProvenanceBadge } from '../common/DataProvenanceBadge';

interface PropertyPassportModalProps {
  isOpen: boolean;
  onClose: () => void;
  passport: PropertyPassportData;
  onExportGeoJson?: () => void;
}

export const PropertyPassportModal: React.FC<PropertyPassportModalProps> = ({
  isOpen,
  onClose,
  passport,
  onExportGeoJson
}) => {
  if (!isOpen) return null;

  // Construct verification URL for QR code (Monochrome: black background, white code)
  const verificationTarget = passport.verificationUrl;
  const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(
    verificationTarget
  )}&bgcolor=000000&color=ffffff`;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn select-text">
      <div className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto gis-glass-panel rounded-3xl border border-white/20 shadow-2xl p-6 text-zinc-100 custom-scrollbar">
        {/* Top Header */}
        <div className="flex items-start justify-between pb-4 border-b border-zinc-800 mb-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold bg-white text-black">
                BHU3D PROPERTY PASSPORT
              </span>
              <span className="px-2 py-0.5 rounded-md text-[10px] font-mono bg-zinc-900 text-zinc-400 border border-zinc-800">
                {passport.version}
              </span>
            </div>
            <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
              <Building className="w-5 h-5 text-white" />
              <span>{passport.buildingName}</span>
            </h2>
            <p className="text-xs text-zinc-400 mt-0.5">{passport.locality}</p>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-zinc-900 text-zinc-400 hover:text-white hover:bg-zinc-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Prominent Provenance Disclaimer Notice */}
        <div className="mb-4 p-3 rounded-2xl bg-zinc-900 border border-zinc-700 text-xs text-zinc-300 space-y-1">
          <div className="font-bold flex items-center gap-1.5 text-white">
            <AlertTriangle className="w-4 h-4 text-white shrink-0" />
            <span>Smart India Hackathon Prototype Record</span>
          </div>
          <p className="text-[11px] leading-relaxed text-zinc-400 font-sans">
            This passport is generated by the Bhu3D 3D vertical cadastre research platform. All 3D geometry is derived from open spatial data and LiDAR surveys. It does not constitute a legally certified property title.
          </p>
        </div>

        {/* Main Grid: Passport Specs + QR Code */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
          {/* Key Reference Specs (2 Cols) */}
          <div className="md:col-span-2 space-y-2 text-xs divide-y divide-zinc-800/80 font-medium">
            <div className="flex items-center justify-between pt-1">
              <span className="text-zinc-400">Bhu3D Reference:</span>
              <span className="font-mono text-white font-bold">{passport.bhu3dReference}</span>
            </div>

            <div className="flex items-center justify-between pt-2">
              <span className="text-zinc-400">Official Government ULPIN:</span>
              <span className="font-mono text-zinc-300 font-bold bg-zinc-900 px-2 py-0.5 rounded border border-zinc-700">
                {passport.officialUlpin}
              </span>
            </div>

            <div className="flex items-center justify-between pt-2">
              <span className="text-zinc-400">Centroid Coordinates:</span>
              <span className="font-mono text-zinc-200 text-[11px]">
                {passport.coordinates.latitude.toFixed(6)}° N, {passport.coordinates.longitude.toFixed(6)}° E
              </span>
            </div>

            <div className="flex items-center justify-between pt-2">
              <span className="text-zinc-400">Ground Footprint Area:</span>
              <span className="font-mono text-white font-semibold">
                {Math.round(passport.footprintAreaSqM).toLocaleString()} m²
              </span>
            </div>

            <div className="flex items-center justify-between pt-2">
              <span className="text-zinc-400">Derived Height & Floors:</span>
              <span className="font-mono text-white">
                {passport.heightMeters.toFixed(1)}m · {passport.estimatedFloors} Floors (Estimated)
              </span>
            </div>

            {passport.calculatedVolumeM3 && (
              <div className="flex items-center justify-between pt-2">
                <span className="text-zinc-400">Calculated 3D Volume:</span>
                <span className="font-mono text-white font-bold">
                  {Math.round(passport.calculatedVolumeM3).toLocaleString()} m³
                </span>
              </div>
            )}

            <div className="flex items-center justify-between pt-2">
              <span className="text-zinc-400">Confidence Score:</span>
              <span className="font-mono text-white font-bold">
                {passport.confidence.score}% ({passport.confidence.quality} QUALITY)
              </span>
            </div>

            <div className="flex items-center justify-between pt-2">
              <span className="text-zinc-400">Geometric Validation:</span>
              <span className="font-mono text-zinc-300 font-bold">
                {passport.validation.overallStatus}
              </span>
            </div>
          </div>

          {/* QR Verification Section */}
          <div className="flex flex-col items-center justify-center p-3 rounded-2xl bg-zinc-950 border border-zinc-800 text-center">
            <span className="text-[10px] font-mono uppercase text-white font-bold mb-1.5 flex items-center gap-1">
              <QrCode className="w-3.5 h-3.5" />
              <span>QR Verification</span>
            </span>

            <div className="p-2 rounded-xl bg-black border border-zinc-800 shadow-inner">
              <img
                src={qrCodeUrl}
                alt="Bhu3D Property Verification QR"
                className="w-32 h-32 rounded-lg invert"
              />
            </div>

            <span className="text-[9px] font-mono text-zinc-500 mt-2 block break-all">
              /property/{passport.buildingId}/verify
            </span>
            <span className="text-[8px] text-zinc-400 mt-0.5">
              Bhu3D Prototype Verification
            </span>
          </div>
        </div>

        {/* Evidence Breakdown Section */}
        <div className="mb-4 p-3 rounded-2xl bg-zinc-900 border border-zinc-800 text-xs">
          <span className="font-bold text-white uppercase tracking-wider text-[11px] block mb-2">
            Provenance Audit Trail
          </span>
          <div className="space-y-1.5 divide-y divide-zinc-800">
            {passport.evidence.map((ev) => (
              <div key={ev.id} className="pt-1.5 flex items-center justify-between">
                <div className="pr-2">
                  <span className="text-zinc-400 block text-[10px]">{ev.category}</span>
                  <span className="text-zinc-200 font-medium text-[11px]">{ev.source}</span>
                  {ev.reasonUnavailable && (
                    <span className="text-zinc-400 block text-[10px] italic">
                      {ev.reasonUnavailable}
                    </span>
                  )}
                </div>
                <DataProvenanceBadge status={ev.status} size="sm" showIcon={false} />
              </div>
            ))}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="pt-3 border-t border-zinc-800 flex items-center justify-between">
          <span className="text-[10px] text-zinc-500 font-mono">
            Generated: {new Date(passport.generatedTimestamp).toLocaleString()}
          </span>

          <div className="flex items-center gap-2">
            {onExportGeoJson && (
              <button
                onClick={onExportGeoJson}
                className="px-3 py-2 rounded-xl bg-zinc-900 hover:bg-zinc-800 text-zinc-200 font-semibold text-xs border border-zinc-700 flex items-center gap-1.5 transition-all"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Export GeoJSON</span>
              </button>
            )}

            <button
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-white hover:bg-zinc-200 text-black font-semibold text-xs transition-all shadow-sm"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
